# Schema for configuration files of the Linked Image field.

field.storage_settings.image_link:
  type: field.storage_settings.file
  label: 'Linked image settings'
  mapping:
    default_image:
      type: field_default_image
      label: 'Default value'

field.field_settings.image_link:
  type: base_file_field_field_settings
  label: 'Linked image settings'
  mapping:
    max_resolution:
      type: string
      label: 'Maximum image resolution'
    min_resolution:
      type: string
      label: 'Minimum image resolution'
    alt_field:
      type: boolean
      label: 'Enable Alt field'
    alt_field_required:
      type: boolean
      label: 'Alt field required'
    title_field:
      type: boolean
      label: 'Enable Title field'
    title_field_required:
      type: boolean
      label: 'Title field required'
    default_image:
      type: field_default_image
      label: 'Default value'
    link_title:
      type: integer
      label: 'Allow link text'
    link_type:
      type: integer
      label: 'Allowed link type'

field.value.image_link:
  type: field_default_image
  label: 'Default value'

field.formatter.settings.image_link:
  type: mapping
  label: 'Linked image field display format settings'
  mapping:
    image_link:
      type: string
      label: 'Link image to'
    image_style:
      type: string
      label: 'Image style'
    link_title_display:
      type: boolean
      label: 'Show link title'
    link_title_tag:
      type: string
      label: 'Link title tag'
    link_title_position:
      type: string
      label: 'Link title position'
    link_rel:
      type: string
      label: 'Add rel="nofollow" to links'
    link_target:
      type: string
      label: 'Open link in new window'
    svg_render_as_image:
      type: boolean
      label: 'Render SVG as image'
    svg_attributes:
      type: mapping
      label: 'SVG attributes'
      mapping:
        width:
          type: integer
          label: 'SVG width'
        height:
          type: integer
          label: 'SVG height'

field.widget.settings.image_link:
  type: mapping
  label: 'Linked image field display format settings'
  mapping:
    progress_indicator:
      type: string
      label: 'Progress indicator'
    preview_image_style:
      type: string
      label: 'Preview image style'
