views.filter_value.views_dates_date_generic:
  type: views.filter_value.numeric
  label: 'Date'
  mapping:
    type:
      type: string
      label: 'Type'

views.filter.views_dates_date_generic:
  type: views.filter.numeric
  label: 'Date'
  mapping:
    type:
      type: string
      label: 'Type'
